import Head from "next/head";

// local
import Contact from "@/components/home/Contact";
import Placements from "@/components/home/Placements";
import Hero from "@/components/home/Hero";
import Events from "@/components/home/Events";
import Notices from "@/components/home/Notices";
import AboutAndDirector from "@/components/home/About-director";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Events />
      <AboutAndDirector />
      <Notices />
      <Contact />
      <Placements />
    </>
  );
}
