import Head from "next/head";

// local
import Apply from "@/components/home/Apply";
import FAQs from "@/components/home/FAQs";
import Footer from "@/components/home/Footer";
import Contact from "@/components/home/Contact";
import Director from "@/components/home/Director";
import Vision from "@/components/home/Vision";
import Placements from "@/components/home/Placements";
import Achievements from "@/components/home/Achievements";
import Hero from "@/components/home/Hero";
import Events from "@/components/home/Events";
import Notices from "@/components/home/Notices";
import About from "@/components/home/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Events />
      <Director />
      <Notices />
      {/* <Admission /> */}
      <Vision />
      <Placements />
      <Achievements />
      <About />
      <FAQs />
      <Contact />
      <Apply />
    </>
  );
}
